name: CI

on:
  push:
  pull_request:

jobs:
  quick-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-quick-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-quick-
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Lint with flake8 (strict)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Format check with black
      run: |
        black --check .
      continue-on-error: true

    - name: Import order check with isort  
      run: |
        isort --check-only .
      continue-on-error: true

    - name: Quick smoke test
      run: |
        python -c "
        try:
            import climapan_lab
            print('✓ Package import successful')
        except Exception as e:
            print(f'✗ Package import failed: {e}')
            exit(1)
        "

    - name: Run basic functionality tests only
      run: |
        python -m pytest tests/test_basic_functionality.py -v --tb=line -x 